version: "3.8"

services:
  localstack:
    #    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:3.2
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8050}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3,kms,dynamodb,iam
  redis:
    image: redis
    ports:
      - "6379:6379"
  mail-server:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
