endSessionWithoutDiscovery: true
oidcEndSessionUrl: ${vauthenticator.host}/oidc/logout
auth.oidcIss: ${vauthenticator.host}

event:
  consumer:
    enable:
      logger-event-consumer: true

no-reply:
  mail:
    from: "no-reply@local.com"
    welcomeMailSubject: "welcome mail"
    verificationMailSubject: "verification mail"
    resetPasswordMailSubject: "reset password mail"
    mfaMailSubject: "mfa code"

mfa:
  otp:
    length: 6
    timeToLiveInSeconds: 600

document:
  engine: file-system
  fs-base-path: dist

spring:
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      smtp:
        port: 1025
        auth: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:${server.port}/oauth2/jwks

  redis:
    database: 0
    host: localhost

server:
  port: 9090
  forward-headers-strategy: framework
  servlet:
    context-path: /
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 1KB

management:
  server:
    port: 9090
    servlet:
      context-path: /
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS
password:
  generator-criteria:
    upperCaseCharactersSize: 2
    lowerCaseCharactersSize: 2
    specialCharactersSize: 2
    numberCharactersSize: 2
  policy:
    minSize: 1
    minSpecialSymbol: 1
    enablePasswordReusePrevention: true

vauthenticator:
  host: http://local.api.vauthenticator.com:9090

  dynamo-db:
    account:
      table-name: VAuthenticator_Account_Local_Staging
      cache:
        ttl: 10s
        name: account
      role.table-name: VAuthenticator_Account_Role_Local_Staging
    role:
      table-name: VAuthenticator_Role_Local_Staging
      cache:
        name: role
        ttl: 1m
      protected-from-delete: ROLE_USER,VAUTHENTICATOR_ADMIN
    client-application:
      table-name: VAuthenticator_ClientApplication_Local_Staging
      cache:
        ttl: 10s
        name: client-application
    password-history:
      table-name: VAuthenticator_Password_History_Local_Staging
      history-evaluation-limit: 1
      max-history-allowed-size: 3
    keys:
      signature:
        table-name: VAuthenticator_Signature_Keys_Local_Staging
      mfa:
        table-name: VAuthenticator_Mfa_Keys_Local_Staging
    ticket:
      table-name: VAuthenticator_Ticket_Local_Staging
    mfa_account_methods:
      table-name: VAuthenticator_Mfa_Account_Methods_Local_Staging
iamUserAwsCredentialsProvider: true

aws:
  s3:
    endpointOverride: "http://s3.localhost.localstack.cloud:4566"
  kms:
    endpointOverride: "http://localhost:4566"
  dynamodb:
    endpointOverride: "http://localhost:4566"